// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	proto "pgx-protobuf/proto"
)

type SchemaMigration struct {
	Version string `json:"version"`
}

type TestCol struct {
	ID   int32       `json:"id"`
	Data *proto.Test `json:"data"`
}
